title: daizu39's メモ集積所
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  coderay_line_numbers: true
  syntax_highlighter_opts:
    line_numbers: true
  html_to_native: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers: inline
